// <auto-generated/>

#nullable enable

public partial class Provider
    :
    global::System.IDisposable,
    global::System.IAsyncDisposable,
    global::System.IServiceProvider
{
    private readonly object _sync = new object();

    private global::Provider.Scope? _rootScope;
    private global::Provider.Scope RootScope => _rootScope ??= CreateScope(_sync);

    private bool _isDisposed;

    private global::Singleton1? _singleton1_0;
    private global::Singleton1 Singleton1_0 => _singleton1_0 ??= CreateSingleton1();

    private global::Singleton2? _singleton2_0;
    private global::Singleton2 Singleton2_0 => _singleton2_0 ??= CreateSingleton2();

    private global::Singleton4? _singleton4_0;
    private global::Singleton4 Singleton4_0 => _singleton4_0 ??= CreateSingleton4();

    private global::Singleton5? _singleton5_0;
    private global::Singleton5 Singleton5_0 => _singleton5_0 ??= CreateSingleton5();

    private global::ExternalSingleton1? _externalSingleton1_0;
    private global::ExternalSingleton1 ExternalSingleton1_0 => _externalSingleton1_0 ??= CreateExternalSingleton1();

    private global::ExternalSingleton2? _externalSingleton2_0;
    private global::ExternalSingleton2 ExternalSingleton2_0 => _externalSingleton2_0 ??= CreateExternalSingleton2();

    private global::ExternalSingleton4? _externalSingleton4_0;
    private global::ExternalSingleton4 ExternalSingleton4_0 => _externalSingleton4_0 ??= CreateExternalSingleton4();

    private global::ExternalSingleton5? _externalSingleton5_0;
    private global::ExternalSingleton5 ExternalSingleton5_0 => _externalSingleton5_0 ??= CreateExternalSingleton5();

    private global::Singleton3? _singleton3_0;
    private global::Singleton3 Singleton3_0 => _singleton3_0 ??= FactorySingleton3_0();

    private global::Singleton6? _singleton6_0;
    private global::Singleton6 Singleton6_0 => _singleton6_0 ??= FactorySingleton6_0();

    private global::ExternalSingleton3? _externalSingleton3_0;
    private global::ExternalSingleton3 ExternalSingleton3_0 => _externalSingleton3_0 ??= FactoryExternalSingleton3_0();

    private global::ExternalSingletonInterface6? _externalSingletonInterface6_0;
    private global::ExternalSingletonInterface6 ExternalSingletonInterface6_0 => _externalSingletonInterface6_0 ??= FactoryExternalSingletonInterface6_0();

    public object? GetService(global::System.Type serviceType)
    {
        if (serviceType == typeof(global::Singleton1)) return Singleton1_0;
        if (serviceType == typeof(global::SingletonInterface1)) return Singleton2_0;
        if (serviceType == typeof(global::Singleton2)) return Singleton2_0;
        if (serviceType == typeof(global::SingletonInterface2)) return Singleton2_0;
        if (serviceType == typeof(global::Singleton3)) return Singleton3_0;
        if (serviceType == typeof(global::SingletonInterface4)) return Singleton4_0;
        if (serviceType == typeof(global::Singleton4)) return Singleton4_0;
        if (serviceType == typeof(global::SingletonInterface5)) return Singleton5_0;
        if (serviceType == typeof(global::Singleton6)) return Singleton6_0;
        if (serviceType == typeof(global::ExternalSingleton1)) return ExternalSingleton1_0;
        if (serviceType == typeof(global::ExternalSingletonInterface1)) return ExternalSingleton2_0;
        if (serviceType == typeof(global::ExternalSingleton2)) return ExternalSingleton2_0;
        if (serviceType == typeof(global::ExternalSingletonInterface2)) return ExternalSingleton2_0;
        if (serviceType == typeof(global::ExternalSingleton3)) return ExternalSingleton3_0;
        if (serviceType == typeof(global::ExternalSingletonInterface4)) return ExternalSingleton4_0;
        if (serviceType == typeof(global::ExternalSingleton4)) return ExternalSingleton4_0;
        if (serviceType == typeof(global::ExternalSingletonInterface5)) return ExternalSingleton5_0;
        if (serviceType == typeof(global::ExternalSingletonInterface6)) return ExternalSingletonInterface6_0;
        if (serviceType == typeof(global::Scoped1)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ScopedInterface1)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::Scoped2)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ScopedInterface2)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::Scoped3)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ScopedInterface4)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::Scoped4)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ScopedInterface5)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::Scoped6)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScoped1)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScopedInterface1)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScoped2)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScopedInterface2)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScoped3)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScopedInterface4)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScoped4)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScopedInterface5)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::ExternalScopedInterface6)) return RootScope.GetService(serviceType);
        if (serviceType == typeof(global::Transient1)) return CreateTransient1();
        if (serviceType == typeof(global::TransientInterface1)) return CreateTransient2();
        if (serviceType == typeof(global::Transient2)) return CreateTransient2();
        if (serviceType == typeof(global::TransientInterface2)) return CreateTransient2();
        if (serviceType == typeof(global::Transient3)) return FactoryTransient3_0();
        if (serviceType == typeof(global::TransientInterface4)) return CreateTransient4();
        if (serviceType == typeof(global::Transient4)) return CreateTransient4();
        if (serviceType == typeof(global::TransientInterface5)) return CreateTransient5();
        if (serviceType == typeof(global::Transient6)) return FactoryTransient6_0();
        if (serviceType == typeof(global::ExternalTransient1)) return CreateExternalTransient1();
        if (serviceType == typeof(global::ExternalTransientInterface1)) return CreateExternalTransient2();
        if (serviceType == typeof(global::ExternalTransient2)) return CreateExternalTransient2();
        if (serviceType == typeof(global::ExternalTransientInterface2)) return CreateExternalTransient2();
        if (serviceType == typeof(global::ExternalTransient3)) return FactoryExternalTransient3_0();
        if (serviceType == typeof(global::ExternalTransientInterface4)) return CreateExternalTransient4();
        if (serviceType == typeof(global::ExternalTransient4)) return CreateExternalTransient4();
        if (serviceType == typeof(global::ExternalTransientInterface5)) return CreateExternalTransient5();
        if (serviceType == typeof(global::ExternalTransientInterface6)) return FactoryExternalTransientInterface6_0();

        return null;
    }

    private T GetService<T>()
    {
        return (T)GetService(typeof(T))!;
    }

    private global::Singleton1 CreateSingleton1()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Singleton1();
        }
    }

    private global::Singleton2 CreateSingleton2()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Singleton2();
        }
    }

    private global::Singleton3 FactorySingleton3_0()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Singleton3();
        }
    }

    private global::Singleton4 CreateSingleton4()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Singleton4();
        }
    }

    private global::Singleton5 CreateSingleton5()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Singleton5();
        }
    }

    private global::Singleton6 FactorySingleton6_0()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Singleton6((global::SingletonInterface5)this.GetService(typeof(global::ScopedInterface5))!);
        }
    }

    private global::ExternalSingleton1 CreateExternalSingleton1()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::ExternalSingleton1();
        }
    }

    private global::ExternalSingleton2 CreateExternalSingleton2()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::ExternalSingleton2();
        }
    }

    private global::ExternalSingleton3 FactoryExternalSingleton3_0()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return global::ExternalModule.FactoryExternalSingleton3_0(this);
        }
    }

    private global::ExternalSingleton4 CreateExternalSingleton4()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::ExternalSingleton4();
        }
    }

    private global::ExternalSingleton5 CreateExternalSingleton5()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::ExternalSingleton5();
        }
    }

    private global::ExternalSingletonInterface6 FactoryExternalSingletonInterface6_0()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return global::ExternalModule.FactoryExternalSingletonInterface6_0(this);
        }
    }

    private global::Transient1 CreateTransient1()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Transient1();
        }
    }

    private global::Transient2 CreateTransient2()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Transient2();
        }
    }

    private global::Transient3 FactoryTransient3_0()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Transient3();
        }
    }

    private global::Transient4 CreateTransient4()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Transient4();
        }
    }

    private global::Transient5 CreateTransient5()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Transient5();
        }
    }

    private global::Transient6 FactoryTransient6_0()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Transient6();
        }
    }

    private global::ExternalTransient1 CreateExternalTransient1()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::ExternalTransient1();
        }
    }

    private global::ExternalTransient2 CreateExternalTransient2()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::ExternalTransient2();
        }
    }

    private global::ExternalTransient3 FactoryExternalTransient3_0()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return global::ExternalModule.FactoryExternalTransient3_0(this);
        }
    }

    private global::ExternalTransient4 CreateExternalTransient4()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::ExternalTransient4();
        }
    }

    private global::ExternalTransient5 CreateExternalTransient5()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::ExternalTransient5();
        }
    }

    private global::ExternalTransientInterface6 FactoryExternalTransientInterface6_0()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return global::ExternalModule.FactoryExternalTransientInterface6_0(this);
        }
    }

    private global::Provider.Scope CreateScope(object? sync)
    {
        ThrowIfDisposed();
        return new global::Provider.Scope(this, sync);
    }

    public void Dispose()
    {
        lock (_sync)
        {
            if (_isDisposed)
            {
                return;
            }

            _isDisposed = true;
        }

        if (_rootScope != null) _rootScope.Dispose();
    }

    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
    {
        lock (_sync)
        {
            if (_isDisposed)
            {
                return;
            }

            _isDisposed = true;
        }

        if (_rootScope != null) await _rootScope.DisposeAsync();
    }

    private void ThrowIfDisposed()
    {
        if (_isDisposed)
        {
            throw new global::System.ObjectDisposedException("Provider");
        }
    }
}