// <auto-generated/>

#nullable enable

[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
file class GeneratedServiceProviderModuleAttribute : global::System.Attribute
{
}

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
file class SingletonAttribute : global::System.Attribute
{
    public SingletonAttribute(
        global::System.Type serviceType,
        global::System.Type? implementationType = null,
        string? factory = null,
        params global::System.Type[] registerAlsoAs)
    {
    }
}

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
file class ScopedAttribute : global::System.Attribute
{
    public ScopedAttribute(
        global::System.Type serviceType,
        global::System.Type? implementationType = null,
        string? factory = null,
        params global::System.Type[] registerAlsoAs)
    {
    }
}

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
file class TransientAttribute : global::System.Attribute
{
    public TransientAttribute(
        global::System.Type serviceType,
        global::System.Type? implementationType = null,
        string? factory = null,
        params global::System.Type[] registerAlsoAs)
    {
    }
}

namespace Test.Nested
{
    [Singleton(typeof(global::Test.Nested.Singleton1), null, null, typeof(global::Test.Nested.SingletonInterface1))]
    [Singleton(typeof(global::Test.Nested.Singleton2), null, null, typeof(global::Test.Nested.SingletonInterface1), typeof(global::Test.Nested.SingletonInterface2))]
    [Singleton(typeof(global::Test.Nested.Singleton3), null, "global::Test.Nested.Module.FactorySingleton3_0")]
    [Singleton(typeof(global::Test.Nested.SingletonInterface4), typeof(global::Test.Nested.Singleton4), null, typeof(global::Test.Nested.Singleton4))]
    [Singleton(typeof(global::Test.Nested.SingletonInterface5), typeof(global::Test.Nested.Singleton5), null)]
    [Singleton(typeof(global::Test.Nested.SingletonInterface6), null, "global::Test.Nested.Module.FactorySingletonInterface6_0")]
    [Scoped(typeof(global::Test.Nested.Scoped1), null, null, typeof(global::Test.Nested.ScopedInterface1))]
    [Scoped(typeof(global::Test.Nested.Scoped2), null, null, typeof(global::Test.Nested.ScopedInterface1), typeof(global::Test.Nested.ScopedInterface2))]
    [Scoped(typeof(global::Test.Nested.Scoped3), null, "global::Test.Nested.Module.FactoryScoped3_0")]
    [Scoped(typeof(global::Test.Nested.ScopedInterface4), typeof(global::Test.Nested.Scoped4), null, typeof(global::Test.Nested.Scoped4))]
    [Scoped(typeof(global::Test.Nested.ScopedInterface5), typeof(global::Test.Nested.Scoped5), null)]
    [Scoped(typeof(global::Test.Nested.ScopedInterface6), null, "global::Test.Nested.Module.FactoryScopedInterface6_0")]
    [Transient(typeof(global::Test.Nested.Transient1), null, null, typeof(global::Test.Nested.TransientInterface1))]
    [Transient(typeof(global::Test.Nested.Transient2), null, null, typeof(global::Test.Nested.TransientInterface1), typeof(global::Test.Nested.TransientInterface2))]
    [Transient(typeof(global::Test.Nested.Transient3), null, "global::Test.Nested.Module.FactoryTransient3_0")]
    [Transient(typeof(global::Test.Nested.TransientInterface4), typeof(global::Test.Nested.Transient4), null, typeof(global::Test.Nested.Transient4))]
    [Transient(typeof(global::Test.Nested.TransientInterface5), typeof(global::Test.Nested.Transient5), null)]
    [Transient(typeof(global::Test.Nested.TransientInterface6), null, "global::Test.Nested.Module.FactoryTransientInterface6_0")]
    [Singleton(typeof(global::ExternalSingleton1), null, null, typeof(global::ExternalSingletonInterface1))]
    [Singleton(typeof(global::ExternalSingleton2), null, null, typeof(global::ExternalSingletonInterface1), typeof(global::ExternalSingletonInterface2))]
    [Singleton(typeof(global::ExternalSingleton3), null, "global::Test.Nested.Module.FactoryExternalSingleton3_0")]
    [Singleton(typeof(global::ExternalSingletonInterface4), typeof(global::ExternalSingleton4), null, typeof(global::ExternalSingleton4))]
    [Singleton(typeof(global::ExternalSingletonInterface5), typeof(global::ExternalSingleton5), null)]
    [Singleton(typeof(global::ExternalSingletonInterface6), null, "global::Test.Nested.Module.FactoryExternalSingletonInterface6_0")]
    [Scoped(typeof(global::ExternalScoped1), null, null, typeof(global::ExternalScopedInterface1))]
    [Scoped(typeof(global::ExternalScoped2), null, null, typeof(global::ExternalScopedInterface1), typeof(global::ExternalScopedInterface2))]
    [Scoped(typeof(global::ExternalScoped3), null, "global::Test.Nested.Module.FactoryExternalScoped3_0")]
    [Scoped(typeof(global::ExternalScopedInterface4), typeof(global::ExternalScoped4), null, typeof(global::ExternalScoped4))]
    [Scoped(typeof(global::ExternalScopedInterface5), typeof(global::ExternalScoped5), null)]
    [Scoped(typeof(global::ExternalScopedInterface6), null, "global::Test.Nested.Module.FactoryExternalScopedInterface6_0")]
    [Transient(typeof(global::ExternalTransient1), null, null, typeof(global::ExternalTransientInterface1))]
    [Transient(typeof(global::ExternalTransient2), null, null, typeof(global::ExternalTransientInterface1), typeof(global::ExternalTransientInterface2))]
    [Transient(typeof(global::ExternalTransient3), null, "global::Test.Nested.Module.FactoryExternalTransient3_0")]
    [Transient(typeof(global::ExternalTransientInterface4), typeof(global::ExternalTransient4), null, typeof(global::ExternalTransient4))]
    [Transient(typeof(global::ExternalTransientInterface5), typeof(global::ExternalTransient5), null)]
    [Transient(typeof(global::ExternalTransientInterface6), null, "global::Test.Nested.Module.FactoryExternalTransientInterface6_0")]
    [GeneratedServiceProviderModuleAttribute]
    public partial class Module
    {
        public static global::Test.Nested.Singleton3 FactorySingleton3_0(global::System.IServiceProvider _)
        {
            return new global::Test.Nested.Singleton3();
        }

        public static global::Test.Nested.SingletonInterface6 FactorySingletonInterface6_0(global::System.IServiceProvider x)
        {
            return new global::Test.Nested.Singleton6((global::Test.Nested.SingletonInterface5)x.GetService(typeof(global::Test.Nested.SingletonInterface5))!);
        }

        public static global::Test.Nested.Scoped3 FactoryScoped3_0(global::System.IServiceProvider _)
        {
            return new global::Test.Nested.Scoped3();
        }

        public static global::Test.Nested.ScopedInterface6 FactoryScopedInterface6_0(global::System.IServiceProvider x)
        {
            global::Test.Nested.ScopedInterface5 scopedInterface5 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Test.Nested.ScopedInterface5>(x);
            return new global::Test.Nested.Scoped6(scopedInterface5);
        }

        public static global::Test.Nested.Transient3 FactoryTransient3_0(global::System.IServiceProvider _)
        {
            return new global::Test.Nested.Transient3();
        }

        public static global::Test.Nested.TransientInterface6 FactoryTransientInterface6_0(global::System.IServiceProvider _)
        {
            return new global::Test.Nested.Transient6();
        }

        public static global::ExternalSingleton3 FactoryExternalSingleton3_0(global::System.IServiceProvider serviceProvider)
        {
            return global::ExternalModule.FactoryExternalSingleton3_0(serviceProvider);
        }

        public static global::ExternalSingletonInterface6 FactoryExternalSingletonInterface6_0(global::System.IServiceProvider serviceProvider)
        {
            return global::ExternalModule.FactoryExternalSingletonInterface6_0(serviceProvider);
        }

        public static global::ExternalScoped3 FactoryExternalScoped3_0(global::System.IServiceProvider serviceProvider)
        {
            return global::ExternalModule.FactoryExternalScoped3_0(serviceProvider);
        }

        public static global::ExternalScopedInterface6 FactoryExternalScopedInterface6_0(global::System.IServiceProvider serviceProvider)
        {
            return global::ExternalModule.FactoryExternalScopedInterface6_0(serviceProvider);
        }

        public static global::ExternalTransient3 FactoryExternalTransient3_0(global::System.IServiceProvider serviceProvider)
        {
            return global::ExternalModule.FactoryExternalTransient3_0(serviceProvider);
        }

        public static global::ExternalTransientInterface6 FactoryExternalTransientInterface6_0(global::System.IServiceProvider serviceProvider)
        {
            return global::ExternalModule.FactoryExternalTransientInterface6_0(serviceProvider);
        }
    }
}