// <auto-generated/>

#nullable enable

public partial class Provider
{
    public class Scope
        :
        global::System.IDisposable,
        global::System.IAsyncDisposable,
        global::System.IServiceProvider
    {
        private readonly object _sync = new object();
        private readonly global::Provider _root;

        private bool _isDisposed;

        private global::Scoped1? _scoped1_0;
        private global::Scoped1 Scoped1_0 => _scoped1_0 ??= CreateScoped1();

        private global::Scoped2? _scoped2_0;
        private global::Scoped2 Scoped2_0 => _scoped2_0 ??= CreateScoped2();

        private global::Scoped4? _scoped4_0;
        private global::Scoped4 Scoped4_0 => _scoped4_0 ??= CreateScoped4();

        private global::Scoped5? _scoped5_0;
        private global::Scoped5 Scoped5_0 => _scoped5_0 ??= CreateScoped5();

        private global::ExternalScoped1? _externalScoped1_0;
        private global::ExternalScoped1 ExternalScoped1_0 => _externalScoped1_0 ??= CreateExternalScoped1();

        private global::ExternalScoped2? _externalScoped2_0;
        private global::ExternalScoped2 ExternalScoped2_0 => _externalScoped2_0 ??= CreateExternalScoped2();

        private global::ExternalScoped4? _externalScoped4_0;
        private global::ExternalScoped4 ExternalScoped4_0 => _externalScoped4_0 ??= CreateExternalScoped4();

        private global::ExternalScoped5? _externalScoped5_0;
        private global::ExternalScoped5 ExternalScoped5_0 => _externalScoped5_0 ??= CreateExternalScoped5();

        private global::Scoped3? _scoped3_0;
        private global::Scoped3 Scoped3_0 => _scoped3_0 ??= FactoryScoped3_0();

        private global::Scoped6? _scoped6_0;
        private global::Scoped6 Scoped6_0 => _scoped6_0 ??= FactoryScoped6_0();

        private global::ExternalScoped3? _externalScoped3_0;
        private global::ExternalScoped3 ExternalScoped3_0 => _externalScoped3_0 ??= FactoryExternalScoped3_0();

        private global::ExternalScopedInterface6? _externalScopedInterface6_0;
        private global::ExternalScopedInterface6 ExternalScopedInterface6_0 => _externalScopedInterface6_0 ??= FactoryExternalScopedInterface6_0();

        public Scope(global::Provider root, object? sync)
        {
            _root = root;

            if (sync != null)
            {
                _sync = sync;
            }
        }

        public object? GetService(global::System.Type serviceType)
        {
            if (serviceType == typeof(global::Singleton1)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::SingletonInterface1)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Singleton2)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::SingletonInterface2)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Singleton3)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::SingletonInterface4)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Singleton4)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::SingletonInterface5)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Singleton6)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingleton1)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingletonInterface1)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingleton2)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingletonInterface2)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingleton3)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingletonInterface4)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingleton4)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingletonInterface5)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::ExternalSingletonInterface6)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Scoped1)) return Scoped1_0;
            if (serviceType == typeof(global::ScopedInterface1)) return Scoped2_0;
            if (serviceType == typeof(global::Scoped2)) return Scoped2_0;
            if (serviceType == typeof(global::ScopedInterface2)) return Scoped2_0;
            if (serviceType == typeof(global::Scoped3)) return Scoped3_0;
            if (serviceType == typeof(global::ScopedInterface4)) return Scoped4_0;
            if (serviceType == typeof(global::Scoped4)) return Scoped4_0;
            if (serviceType == typeof(global::ScopedInterface5)) return Scoped5_0;
            if (serviceType == typeof(global::Scoped6)) return Scoped6_0;
            if (serviceType == typeof(global::ExternalScoped1)) return ExternalScoped1_0;
            if (serviceType == typeof(global::ExternalScopedInterface1)) return ExternalScoped2_0;
            if (serviceType == typeof(global::ExternalScoped2)) return ExternalScoped2_0;
            if (serviceType == typeof(global::ExternalScopedInterface2)) return ExternalScoped2_0;
            if (serviceType == typeof(global::ExternalScoped3)) return ExternalScoped3_0;
            if (serviceType == typeof(global::ExternalScopedInterface4)) return ExternalScoped4_0;
            if (serviceType == typeof(global::ExternalScoped4)) return ExternalScoped4_0;
            if (serviceType == typeof(global::ExternalScopedInterface5)) return ExternalScoped5_0;
            if (serviceType == typeof(global::ExternalScopedInterface6)) return ExternalScopedInterface6_0;
            if (serviceType == typeof(global::Transient1)) return _root.CreateTransient1();
            if (serviceType == typeof(global::TransientInterface1)) return _root.CreateTransient2();
            if (serviceType == typeof(global::Transient2)) return _root.CreateTransient2();
            if (serviceType == typeof(global::TransientInterface2)) return _root.CreateTransient2();
            if (serviceType == typeof(global::Transient3)) return _root.FactoryTransient3_0();
            if (serviceType == typeof(global::TransientInterface4)) return _root.CreateTransient4();
            if (serviceType == typeof(global::Transient4)) return _root.CreateTransient4();
            if (serviceType == typeof(global::TransientInterface5)) return _root.CreateTransient5();
            if (serviceType == typeof(global::Transient6)) return _root.FactoryTransient6_0();
            if (serviceType == typeof(global::ExternalTransient1)) return _root.CreateExternalTransient1();
            if (serviceType == typeof(global::ExternalTransientInterface1)) return _root.CreateExternalTransient2();
            if (serviceType == typeof(global::ExternalTransient2)) return _root.CreateExternalTransient2();
            if (serviceType == typeof(global::ExternalTransientInterface2)) return _root.CreateExternalTransient2();
            if (serviceType == typeof(global::ExternalTransient3)) return _root.FactoryExternalTransient3_0();
            if (serviceType == typeof(global::ExternalTransientInterface4)) return _root.CreateExternalTransient4();
            if (serviceType == typeof(global::ExternalTransient4)) return _root.CreateExternalTransient4();
            if (serviceType == typeof(global::ExternalTransientInterface5)) return _root.CreateExternalTransient5();
            if (serviceType == typeof(global::ExternalTransientInterface6)) return _root.FactoryExternalTransientInterface6_0();

            return null;
        }

        private T GetService<T>()
        {
            return (T)GetService(typeof(T))!;
        }

        private global::Scoped1 CreateScoped1()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::Scoped1();
            }
        }

        private global::Scoped2 CreateScoped2()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::Scoped2();
            }
        }

        private global::Scoped3 FactoryScoped3_0()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::Scoped3();
            }
        }

        private global::Scoped4 CreateScoped4()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::Scoped4();
            }
        }

        private global::Scoped5 CreateScoped5()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::Scoped5();
            }
        }

        private global::Scoped6 FactoryScoped6_0()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::Scoped6();
            }
        }

        private global::ExternalScoped1 CreateExternalScoped1()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::ExternalScoped1();
            }
        }

        private global::ExternalScoped2 CreateExternalScoped2()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::ExternalScoped2();
            }
        }

        private global::ExternalScoped3 FactoryExternalScoped3_0()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return global::ExternalModule.FactoryExternalScoped3_0(this);
            }
        }

        private global::ExternalScoped4 CreateExternalScoped4()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::ExternalScoped4();
            }
        }

        private global::ExternalScoped5 CreateExternalScoped5()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::ExternalScoped5();
            }
        }

        private global::ExternalScopedInterface6 FactoryExternalScopedInterface6_0()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return global::ExternalModule.FactoryExternalScopedInterface6_0(this);
            }
        }

        public void Dispose()
        {
            lock (_sync)
            {
                if (_isDisposed)
                {
                    return;
                }

                _isDisposed = true;
            }
        }

        public global::System.Threading.Tasks.ValueTask DisposeAsync()
        {
            lock (_sync)
            {
                if (_isDisposed)
                {
                    return default;
                }

                _isDisposed = true;
            }

            return default;
        }

        private void ThrowIfDisposed()
        {
            if (_isDisposed)
            {
                throw new global::System.ObjectDisposedException("Provider.Scope");
            }
        }
    }
}