// <auto-generated/>

#nullable enable

[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
file class GeneratedServiceProviderModuleAttribute : global::System.Attribute
{
}

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
file class SingletonAttribute : global::System.Attribute
{
    public SingletonAttribute(
        global::System.Type serviceType,
        global::System.Type? implementationType = null,
        string? factory = null,
        params global::System.Type[] registerAlsoAs)
    {
    }
}

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
file class ScopedAttribute : global::System.Attribute
{
    public ScopedAttribute(
        global::System.Type serviceType,
        global::System.Type? implementationType = null,
        string? factory = null,
        params global::System.Type[] registerAlsoAs)
    {
    }
}

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
file class TransientAttribute : global::System.Attribute
{
    public TransientAttribute(
        global::System.Type serviceType,
        global::System.Type? implementationType = null,
        string? factory = null,
        params global::System.Type[] registerAlsoAs)
    {
    }
}

[global::Singleton(typeof(global::Singleton1), null, null, typeof(global::SingletonInterface1))]
[global::Singleton(typeof(global::Singleton2), null, null, typeof(global::SingletonInterface1), typeof(global::SingletonInterface2))]
[global::Singleton(typeof(global::Singleton3), null, "global::Module.FactorySingleton3_0")]
[global::Singleton(typeof(global::SingletonInterface4), typeof(global::Singleton4), null, typeof(global::Singleton4))]
[global::Singleton(typeof(global::SingletonInterface5), typeof(global::Singleton5), null)]
[global::Singleton(typeof(global::SingletonInterface6), null, "global::Module.FactorySingletonInterface6_0")]
[global::Scoped(typeof(global::Scoped1), null, null, typeof(global::ScopedInterface1))]
[global::Scoped(typeof(global::Scoped2), null, null, typeof(global::ScopedInterface1), typeof(global::ScopedInterface2))]
[global::Scoped(typeof(global::Scoped3), null, "global::Module.FactoryScoped3_0")]
[global::Scoped(typeof(global::ScopedInterface4), typeof(global::Scoped4), null, typeof(global::Scoped4))]
[global::Scoped(typeof(global::ScopedInterface5), typeof(global::Scoped5), null)]
[global::Scoped(typeof(global::ScopedInterface6), null, "global::Module.FactoryScopedInterface6_0")]
[global::Transient(typeof(global::Transient1), null, null, typeof(global::TransientInterface1))]
[global::Transient(typeof(global::Transient2), null, null, typeof(global::TransientInterface1), typeof(global::TransientInterface2))]
[global::Transient(typeof(global::Transient3), null, "global::Module.FactoryTransient3_0")]
[global::Transient(typeof(global::TransientInterface4), typeof(global::Transient4), null, typeof(global::Transient4))]
[global::Transient(typeof(global::TransientInterface5), typeof(global::Transient5), null)]
[global::Transient(typeof(global::TransientInterface6), null, "global::Module.FactoryTransientInterface6_0")]
[global::Singleton(typeof(global::ExternalSingleton1), null, null, typeof(global::ExternalSingletonInterface1))]
[global::Singleton(typeof(global::ExternalSingleton2), null, null, typeof(global::ExternalSingletonInterface1), typeof(global::ExternalSingletonInterface2))]
[global::Singleton(typeof(global::ExternalSingleton3), null, "global::Module.FactoryExternalSingleton3_0")]
[global::Singleton(typeof(global::ExternalSingletonInterface4), typeof(global::ExternalSingleton4), null, typeof(global::ExternalSingleton4))]
[global::Singleton(typeof(global::ExternalSingletonInterface5), typeof(global::ExternalSingleton5), null)]
[global::Singleton(typeof(global::ExternalSingletonInterface6), null, "global::Module.FactoryExternalSingletonInterface6_0")]
[global::Scoped(typeof(global::ExternalScoped1), null, null, typeof(global::ExternalScopedInterface1))]
[global::Scoped(typeof(global::ExternalScoped2), null, null, typeof(global::ExternalScopedInterface1), typeof(global::ExternalScopedInterface2))]
[global::Scoped(typeof(global::ExternalScoped3), null, "global::Module.FactoryExternalScoped3_0")]
[global::Scoped(typeof(global::ExternalScopedInterface4), typeof(global::ExternalScoped4), null, typeof(global::ExternalScoped4))]
[global::Scoped(typeof(global::ExternalScopedInterface5), typeof(global::ExternalScoped5), null)]
[global::Scoped(typeof(global::ExternalScopedInterface6), null, "global::Module.FactoryExternalScopedInterface6_0")]
[global::Transient(typeof(global::ExternalTransient1), null, null, typeof(global::ExternalTransientInterface1))]
[global::Transient(typeof(global::ExternalTransient2), null, null, typeof(global::ExternalTransientInterface1), typeof(global::ExternalTransientInterface2))]
[global::Transient(typeof(global::ExternalTransient3), null, "global::Module.FactoryExternalTransient3_0")]
[global::Transient(typeof(global::ExternalTransientInterface4), typeof(global::ExternalTransient4), null, typeof(global::ExternalTransient4))]
[global::Transient(typeof(global::ExternalTransientInterface5), typeof(global::ExternalTransient5), null)]
[global::Transient(typeof(global::ExternalTransientInterface6), null, "global::Module.FactoryExternalTransientInterface6_0")]
[global::GeneratedServiceProviderModuleAttribute]
public partial class Module
{
    public static global::Singleton3 FactorySingleton3_0(global::System.IServiceProvider _)
    {
        return new global::Singleton3();
    }

    public static global::SingletonInterface6 FactorySingletonInterface6_0(global::System.IServiceProvider x)
    {
        return new global::Singleton6((global::SingletonInterface5)x.GetService(typeof(global::ScopedInterface5))!);
    }

    public static global::Scoped3 FactoryScoped3_0(global::System.IServiceProvider _)
    {
        return new global::Scoped3();
    }

    public static global::ScopedInterface6 FactoryScopedInterface6_0(global::System.IServiceProvider _)
    {
        return new global::Scoped6();
    }

    public static global::Transient3 FactoryTransient3_0(global::System.IServiceProvider _)
    {
        return new global::Transient3();
    }

    public static global::TransientInterface6 FactoryTransientInterface6_0(global::System.IServiceProvider _)
    {
        return new global::Transient6();
    }

    public static global::ExternalSingleton3 FactoryExternalSingleton3_0(global::System.IServiceProvider serviceProvider)
    {
        return global::ExternalModule.FactoryExternalSingleton3_0(serviceProvider);
    }

    public static global::ExternalSingletonInterface6 FactoryExternalSingletonInterface6_0(global::System.IServiceProvider serviceProvider)
    {
        return global::ExternalModule.FactoryExternalSingletonInterface6_0(serviceProvider);
    }

    public static global::ExternalScoped3 FactoryExternalScoped3_0(global::System.IServiceProvider serviceProvider)
    {
        return global::ExternalModule.FactoryExternalScoped3_0(serviceProvider);
    }

    public static global::ExternalScopedInterface6 FactoryExternalScopedInterface6_0(global::System.IServiceProvider serviceProvider)
    {
        return global::ExternalModule.FactoryExternalScopedInterface6_0(serviceProvider);
    }

    public static global::ExternalTransient3 FactoryExternalTransient3_0(global::System.IServiceProvider serviceProvider)
    {
        return global::ExternalModule.FactoryExternalTransient3_0(serviceProvider);
    }

    public static global::ExternalTransientInterface6 FactoryExternalTransientInterface6_0(global::System.IServiceProvider serviceProvider)
    {
        return global::ExternalModule.FactoryExternalTransientInterface6_0(serviceProvider);
    }
}