// <auto-generated/>

#nullable enable

public partial class Provider
    :
    global::System.IDisposable,
    global::System.IAsyncDisposable,
    global::System.IServiceProvider
{
    private readonly object _sync = new object();

    private global::Provider.Scope? _rootScope;
    private global::Provider.Scope RootScope => _rootScope ??= CreateScope(_sync);

    private bool _isDisposed;

    private global::Service? _service_0;
    private global::Service Service_0 => _service_0 ??= CreateService();

    private global::Dependency1? _dependency1_0;
    private global::Dependency1 Dependency1_0 => _dependency1_0 ??= CreateDependency1();

    private global::Dependency2? _dependency2_0;
    private global::Dependency2 Dependency2_0 => _dependency2_0 ??= CreateDependency2();

    public object? GetService(global::System.Type serviceType)
    {
        if (serviceType == typeof(global::Service)) return Service_0;
        if (serviceType == typeof(global::Dependency1)) return Dependency1_0;
        if (serviceType == typeof(global::Dependency2)) return Dependency2_0;

        return null;
    }

    private T GetService<T>()
    {
        return (T)GetService(typeof(T))!;
    }

    private global::Service CreateService()
    {
        lock (_sync)
        {
            ThrowIfDisposed();

            return new global::Service(
                GetService<global::Dependency1>(),
                GetService<global::Dependency2>()
            );
        }
    }

    private global::Dependency1 CreateDependency1()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Dependency1();
        }
    }

    private global::Dependency2 CreateDependency2()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            return new global::Dependency2();
        }
    }

    private global::Provider.Scope CreateScope(object? sync)
    {
        ThrowIfDisposed();
        return new global::Provider.Scope(this, sync);
    }

    public void Dispose()
    {
        lock (_sync)
        {
            if (_isDisposed)
            {
                return;
            }

            _isDisposed = true;
        }

        if (_rootScope != null) _rootScope.Dispose();
    }

    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
    {
        lock (_sync)
        {
            if (_isDisposed)
            {
                return;
            }

            _isDisposed = true;
        }

        if (_rootScope != null) await _rootScope.DisposeAsync();
    }

    private void ThrowIfDisposed()
    {
        if (_isDisposed)
        {
            throw new global::System.ObjectDisposedException("Provider");
        }
    }
}