// <auto-generated/>

#nullable enable

public partial class Provider
{
    private class RegistrationModifier
    {
        public static readonly global::Provider.RegistrationModifier Instance;

        static RegistrationModifier()
        {
            Instance = new global::Provider.RegistrationModifier();
        }

        private RegistrationModifier()
        {
        }

        public global::Provider.RegistrationModifier AlsoAsSelf()
        {
            return this;
        }

        public global::Provider.RegistrationModifier AlsoAs(global::System.Type type)
        {
            return this;
        }

        public global::Provider.RegistrationModifier AlsoAs<T>()
        {
            return this;
        }
    }

    private global::Provider.RegistrationModifier ImportModule<T>()
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier ImportModule(global::System.Type moduleType)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddSingleton(global::System.Type serviceType)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddSingleton(global::System.Type serviceType, global::System.Type implementationType)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddSingleton<TService>()
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddSingleton<TService, TImplementation>() where TImplementation : TService
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddSingleton<TService>(global::System.Func<global::System.IServiceProvider, TService> factory)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddScoped(global::System.Type serviceType)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddScoped(global::System.Type serviceType, global::System.Type implementationType)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddScoped<TService>()
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddScoped<TService, TImplementation>() where TImplementation : TService
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddScoped<TService>(global::System.Func<global::System.IServiceProvider, TService> factory)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddTransient(global::System.Type serviceType)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddTransient(global::System.Type serviceType, global::System.Type implementationType)
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddTransient<TService>()
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddTransient<TService, TImplementation>() where TImplementation : TService
    {
        return global::Provider.RegistrationModifier.Instance;
    }

    private global::Provider.RegistrationModifier AddTransient<TService>(global::System.Func<global::System.IServiceProvider, TService> factory)
    {
        return global::Provider.RegistrationModifier.Instance;
    }
}