// <auto-generated/>

#nullable enable

public partial class Provider
{
    public class Scope
        :
        global::System.IDisposable,
        global::System.IAsyncDisposable,
        global::System.IServiceProvider,
        global::Microsoft.Extensions.DependencyInjection.IServiceScope
    {
        private readonly object _sync = new object();
        private readonly global::Provider _root;

        private bool _isDisposed;

        private global::Dependency5? _dependency5_0;
        private global::Dependency5 Dependency5_0 => _dependency5_0 ??= CreateDependency5_0();

        private global::System.Collections.Generic.IEnumerable<global::Dependency5>? _enumerableDependency5;
        private global::System.Collections.Generic.IEnumerable<global::Dependency5> EnumerableDependency5 => _enumerableDependency5 ??= CreateEnumerableDependency5();

        global::System.IServiceProvider global::Microsoft.Extensions.DependencyInjection.IServiceScope.ServiceProvider => this;

        public Scope(global::Provider root, object? sync)
        {
            _root = root;

            if (sync != null)
            {
                _sync = sync;
            }
        }

        public object? GetService(global::System.Type serviceType)
        {
            if (serviceType == typeof(global::Interface1)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Interface2)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Service)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Dependency4)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Dependency5)) return Dependency5_0;
            if (serviceType == typeof(global::Dependency6)) return _root.CreateDependency6_0();
            if (serviceType == typeof(global::System.Collections.Generic.IEnumerable<global::Interface1>)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::System.Collections.Generic.IEnumerable<global::Interface2>)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::System.Collections.Generic.IEnumerable<global::Interface3>)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::System.Collections.Generic.IEnumerable<global::Dependency4>)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::System.Collections.Generic.IEnumerable<global::Dependency5>)) return EnumerableDependency5;
            if (serviceType == typeof(global::System.Collections.Generic.IEnumerable<global::Dependency6>)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService)) return _root.GetService(serviceType);
            if (serviceType == typeof(global::System.IServiceProvider)) return this;
            if (serviceType == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScope)) return this;

            return null;
        }

        private T GetService<T>()
        {
            return (T)GetService(typeof(T))!;
        }

        private global::Dependency5 CreateDependency5_0()
        {
            lock (_sync)
            {
                ThrowIfDisposed();
                return new global::Dependency5();
            }
        }

        private global::Dependency5[] CreateEnumerableDependency5()
        {
            lock (_sync)
            {
                ThrowIfDisposed();

                return new global::Dependency5[]
                {
                    Dependency5_0
                };
            }
        }

        public void Dispose()
        {
            lock (_sync)
            {
                if (_isDisposed)
                {
                    return;
                }

                _isDisposed = true;
            }
        }

        public global::System.Threading.Tasks.ValueTask DisposeAsync()
        {
            lock (_sync)
            {
                if (_isDisposed)
                {
                    return default;
                }

                _isDisposed = true;
            }

            return default;
        }

        private void ThrowIfDisposed()
        {
            if (_isDisposed)
            {
                throw new global::System.ObjectDisposedException("Provider.Scope");
            }
        }
    }
}